# Generated by Django 4.0.5 on 2022-08-10 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App1', '0002_remove_avatar_avatar_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberuser',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
