# Generated by Django 4.0.5 on 2022-08-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='imagen',
        ),
        migrations.AddField(
            model_name='avatar',
            name='avatar',
            field=models.ImageField(blank=True, default='media\x07vatar\x07vatarDefault.png', null=True, upload_to='avatar'),
        ),
    ]
